apiVersion: apps/v1
kind: Deployment
metadata:
  name: authbackend-deployment
  namespace: fit-namespace
spec:
  selector:
    matchLabels:
      app: authbackend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: authbackend-app
    spec:
      containers:
        - name: authbackend-container
          image: arthuracrs/fit-auth-service:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
          - name: API_PORT
            value: "3001"
          - name: TOKEN_KEY
            value: "token123fom"
          - name: MONGO_URI
            value: "mongodb://admin:secret@mongodb-service:27017/auth?authSource=admin"

